[package]
name = "security"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
tokio-tungstenite = "0.20"
futures = "0.3"
nokhwa = { version = "0.10", features = ["input-native"] }
parking_lot = "0.12"
chrono = "0.4"
log = "0.4"
env_logger = "0.10"